# Compress-ZipFile command data
$Datas = @{
	CompressZipFileSynopsis = ''
	CompressZipFileDescription = ''
	CompressZipFileSetsLiteralPath = ''
	CompressZipFileSetsPath = ''
	CompressZipFileParametersCodePageIdentifier = ''
	CompressZipFileParametersComment = ''
	CompressZipFileParametersEncoding = ''
	CompressZipFileParametersEncryption = ''
	CompressZipFileParametersEntryPathRoot = ''
	CompressZipFileParametersLiteralPath = ''
	CompressZipFileParametersNotTraverseReparsePoints = ''
	CompressZipFileParametersOutputName = ''
	CompressZipFileParametersPassthru = ''
	CompressZipFileParametersPassword = ''
	CompressZipFileParametersPath = ''
	CompressZipFileParametersRecurse = ''
	CompressZipFileParametersSetLastModifiedProperty = ''
	CompressZipFileParametersSortEntries = ''
	CompressZipFileParametersSplit = ''
	CompressZipFileParametersTempLocation = ''
	CompressZipFileParametersUnixTimeFormat = ''
	CompressZipFileParametersWindowsTimeFormat = ''
	CompressZipFileParametersZipErrorAction = ''
	CompressZipFileInputsDescription1 = ''
	CompressZipFileOutputsDescriptionIonicZipZipFile = ''
	CompressZipFileNotes = ''
	CompressZipFileExamplesRemarks1 = ''
}


