# Compress-ZipFile command data
$Datas = @{
	CompressZipFileSynopsis = ''
	CompressZipFileDescription = ''
	CompressZipFileSetsFile = ''
	CompressZipFileSetsSFX = ''
	CompressZipFileSetsUT = ''
	CompressZipFileSetsUTnewest = ''
	CompressZipFileSetsUTnow = ''
	CompressZipFileSetsUToldest = ''
	CompressZipFileParametersCodePageIdentifier = ''
	CompressZipFileParametersComment = ''
	CompressZipFileParametersEncoding = ''
	CompressZipFileParametersEncryption = ''
	CompressZipFileParametersFile = ''
	CompressZipFileParametersName = ''
	CompressZipFileParametersNewUniformTimestamp = ''
	CompressZipFileParametersNotTraverseReparsePoints = ''
	CompressZipFileParametersNowUniformTimestamp = ''
	CompressZipFileParametersOldUniformTimestamp = ''
	CompressZipFileParametersOptions = ''
	CompressZipFileParametersPassthru = ''
	CompressZipFileParametersPassword = ''
	CompressZipFileParametersRecurse = ''
	CompressZipFileParametersSFX = ''
	CompressZipFileParametersSortEntries = ''
	CompressZipFileParametersSplit = ''
	CompressZipFileParametersTempLocation = ''
	CompressZipFileParametersUniformTimestamp = ''
	CompressZipFileParametersUnixTimeFormat = ''
	CompressZipFileParametersWindowsTimeFormat = ''
	CompressZipFileParametersZipErrorAction = ''
	CompressZipFileInputsDescription1 = ''
	CompressZipFileOutputsDescriptionFile = ''
	CompressZipFileOutputsDescriptionIonicZipZipFile = ''
	CompressZipFileOutputsDescriptionSFX = ''
	CompressZipFileOutputsDescriptionSystemIOFileInfo = ''
	CompressZipFileNotes = ''
	CompressZipFileExamplesRemarks1 = ''
}


