ConvertFrom-StringData @' 
 EmptyEnum="L'énumération ne contient aucune entrée."
 PathMustExistNullOrEmpty="Le nom de chemin est null ou vide."
 PathMustExist="Le nom de chemin n'existe pas : {0}"
 IsSubClassOf="L'argument {0} n'est pas une instance dérivée de la classe {1}."
 InvokeEventNotSupported="La valeur '{0}' n'est pas supportée."
 InvalidPassword="Le type de cryptage demandé ('{0}') ,nécessite que le paramètre password soit renseigné."
 SettingEncryption="Le cryptage de l'archive {0} a provoqué l'exception suivante : {1}."
 InvalidSelectionCriteria="La requête est invalide : {0}"
 ConflictingParameter="Les paramètres ou comportements {0} et {0} sont incompatibles."
 ConvertingFile="Conversion de l'archive {1} en une archive autoextractible."
 ErrorSFX="Erreur lors de la création de l'archive autoextractible {0} : {1}"
 ZipArchiveTypeNotSupported="Le type d'objet {0} n'est pas pris en charge pour la lecture d'une archive."
 ZipArchiveReadError="Une erreur s'est produite lors de la lecture de l'archive {0} : {1}."
 ZipArchiveExtractError="Une erreur s'est produite lors de l'extraction de l'archive {0} : {1}."
 ZipArchiveNotFound="L'archive {0} n'existe pas."
'@ 
